### ISSUE TITLE
week 01 作業回饋

### ISSUE THREAD

**Issue by azole** [YulMitz/CloudNative-Yuming#1]
尤敏，你這次的作業把名詞解釋理論跟觀察結合在一起，是很好的作法，以下有幾個可以更好的地方:

- 善用圖片輔助說明
- 可以有更多的好奇心，把老師出的題目當作起點，而不是終點，也就是，你在讀完相關的文章、做完實驗觀察後，自己有沒有對 git 有其他想要探討的問題呢？而不是只回答了作業單上的提問。
- 再來是，commit message style 這題漏寫了？如果是的話，那要更細心一點。

**Comment by YulMitz** [comment]
謝謝老師，我會在作業2盡量融入第一點和第二點
然後我確實漏看了commit message style的部分，所以我花了一點時間補寫了該部分
下次作業會試著更細心！

**Comment by azole** [comment]
好，很好，到時候小組分組的時候，你可以試著提出你的方案在小組內討論，透過課程中的分組活動，去「測試」自己規劃的這個 commit message 規範是否可行，不管最後是可行或不可行（或甚至小組成員願不願意採納），等到職場上，你都會更有底氣，會有屬於自己的經驗跟想法。

下次作業繼續努力，我們每次都進步一些，到課程結束的時候，一定會比現在變得強很多。
